def create_context() -> None: ...
def new_frame() -> None: ...
def begin(window_name: str, closable: bool | None = None, flags=0): ...
def text(text: str) -> None: ...
def button(text: str, width: float = 0.0, height: float = 0.0) -> bool: ...
def input_text(
    label: str,
    value: str,
    buffer_length: int = -1,
    flags: int = 0,
    callback=None,
    user_data=None,
) -> tuple[bool, str]: ...
def input_int(
    label: str,
    value: int,
    buffer_length: int = -1,
    flags: int = 0,
    callback=None,
    user_data=None,
) -> tuple[bool, int]: ...
def slider_float(
    text: str, value: float, min: float, max: float
) -> tuple[None, float]: ...
def show_test_window() -> None: ...
def end() -> None: ...
def render() -> None: ...
def get_draw_data() -> None: ...
def same_line() -> None: ...

WINDOW_NO_TITLE_BAR: int
WINDOW_NO_MOVE: int
WINDOW_NO_RESIZE: int
WINDOW_NO_COLLAPSE: int
STYLE_ALPHA: int
ITEM_DISABLED: int

def set_next_window_size(width: int, height: int): ...
def set_next_window_position(x: int, y: int): ...
def separator(): ...
def get_style(): ...
def push_style_var(flag, value): ...
def pop_style_var(): ...
def push_item_flag(flag, value): ...
def pop_item_flag(): ...
